<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Fields[
  <!ELEMENT Fields ANY>
  <!ELEMENT Field ANY>
  <!ATTLIST Field Id ID #REQUIRED>
  <!ATTLIST Field Title CDATA #REQUIRED>
  <!ATTLIST Field Hidden CDATA #IMPLIED>
  <!ATTLIST Field DefaultValue CDATA #IMPLIED>
]>
<Fields>
  <!-- UI -->
  <Field Id="Rendition_UI_clientServerSyncPublicURL" Title="/responder"></Field>
  <Field Id="Rendition_UI_clientServerSyncURL" Title="/admin/responder"></Field>
  <Field Id="UIHelpers_Debug_Log" Title="Debug Log"></Field>
  <Field Id="UIHelpers_Ok" Title="Ok"></Field>
  <Field Id="UIHelpers_Warning" Title="Warning"></Field>
  <Field Id="UIHelpers_iFrame" Title="iFrame"></Field>
  <Field Id="UIHelpers_Updating" Title="Updating"></Field>
  <Field Id="UIHelpers_Please_Wait" Title="Please Wait..."></Field>
  <Field Id="UIHelpers_Please_wait_while_your_task_is_completed" Title="Please wait while your task is completed."></Field>
  <Field Id="SelectDialog_Select" Title="Select"></Field>
  <Field Id="SelectDialog_Selected" Title="Selected:"></Field>
  <Field Id="SelectDialog_Cancel" Title="Cancel"></Field>
  <Field Id="SelectDialog_This_must_match_a_vaule_from_the_column_x_in_the_table_above" Title="This must match a vaule from the column {0} in the table above."></Field>
  <Field Id="SelectDialog_Invalid_value" Title="Invalid value."></Field>
  <Field Id="SelectDialog_Browse" Title="Browse..."></Field>
  <Field Id="SelectDialog_Ok" Title="Ok"></Field>
  <Field Id="SelectButtonDialog_Ok" Title="Ok"></Field>
  <Field Id="SelectButtonDialog_Cancel" Title="Cancel"></Field>
  <Field Id="SelectButtonDialog_This_must_match_a_vaule_from_the_column_x_in_the_table_above" Title="This must match a vaule from the column {0} in the table above."></Field>
  <Field Id="SelectButtonDialog_Invalid_value" Title="Invalid value."></Field>
  <Field Id="RichTextEditor_You_can_only_insert_jpg_gif_or_png_images" Title="You can only insert .jpg, .gif or .png images"></Field>
  <Field Id="RichTextEditor_Add_A_Link" Title="Add A Link"></Field>
  <Field Id="RichTextEditor_Mode" Title="Mode"></Field>
  <Field Id="RichTextEditor_Bold" Title="Bold"></Field>
  <Field Id="RichTextEditor_Italic" Title="Italic"></Field>
  <Field Id="RichTextEditor_Strike_Through" Title="Strike Through"></Field>
  <Field Id="RichTextEditor_Underline" Title="Underline"></Field>
  <Field Id="RichTextEditor_Justify_Left" Title="Justify Left"></Field>
  <Field Id="RichTextEditor_Justify_Center" Title="Justify Center"></Field>
  <Field Id="RichTextEditor_Justify_Right" Title="Justify Right"></Field>
  <Field Id="RichTextEditor_Justify_Full" Title="Justify Full"></Field>
  <Field Id="RichTextEditor_Indent" Title="Indent"></Field>
  <Field Id="RichTextEditor_Outdent" Title="Outdent"></Field>
  <Field Id="RichTextEditor_Sub_Script" Title="Sub Script"></Field>
  <Field Id="RichTextEditor_Super_Script" Title="Super Script"></Field>
  <Field Id="RichTextEditor_Ordered_List" Title="Ordered List"></Field>
  <Field Id="RichTextEditor_Unordered_List" Title="Unordered List"></Field>
  <Field Id="RichTextEditor_Horizontal_Rule" Title="Horizontal Rule"></Field>
  <Field Id="RichTextEditor_Color" Title="Color"></Field>
  <Field Id="RichTextEditor_Background_Color" Title="Background Color"></Field>
  <Field Id="RichTextEditor_Insert_Image" Title="Insert Image"></Field>
  <Field Id="RichTextEditor_Link" Title="Link"></Field>
  <Field Id="RichTextEditor_Unlink" Title="Unlink"></Field>
  <Field Id="RichTextEditor_Undo" Title="Undo"></Field>
  <Field Id="RichTextEditor_Remove_Formating" Title="Remove Formating"></Field>
  <Field Id="RichTextEditor_Remove_Word_Glyphs" Title="Remove Word Glyphs"></Field>
  <Field Id="RichTextEditor_Clear" Title="Clear"></Field>
  <Field Id="RichTextEditor_Font" Title="Font"></Field>
  <Field Id="RichTextEditor_Font_Size" Title="Font Size"></Field>
  <Field Id="RichTextEditor_Block" Title="Block"></Field>
  <Field Id="RichTextEditor_Rich_Text_Editor" Title="Rich Text Editor"></Field>
  <Field Id="ImageViewer_Image_Viewer" Title="Image Viewer"></Field>
  <Field Id="Grid_Operator_Equal" Title="="></Field>
  <Field Id="Grid_Operator_Like" Title="Like (%=wildcard)"></Field>
  <Field Id="Grid_Operator_Between" Title="Between"></Field>
  <Field Id="Grid_Operator_Greater_Than" Title="Greater Than"></Field>
  <Field Id="Grid_Operator_Less_Than" Title="Less Than"></Field>
  <Field Id="Grid_Operator_Is_Null" Title="Is Null"></Field>
  <Field Id="Grid_Operator_Is_Not_Null" Title="Is Not Null"></Field>
  <Field Id="Grid_OutputFileTypes_CSV_Comma_Seperated_Values" Title="CSV (Comma Seperated Values)"></Field>
  <Field Id="Grid_OutputFileTypes_HTML" Title="HTML (Hypertext Markup Language)"></Field>
  <Field Id="Grid_OutputFileTypes_XML" Title="XML (Extensible Markup Language)"></Field>
  <Field Id="Grid_aggOp_Sum" Title="Sum"></Field>
  <Field Id="Grid_aggOp_Average" Title="Average"></Field>
  <Field Id="Grid_aggOp_Count" Title="Count"></Field>
  <Field Id="Grid_aggOp_Max" Title="Max"></Field>
  <Field Id="Grid_aggOp_Min" Title="Min"></Field>
  <Field Id="Grid_aggOp_Standard_Deviation" Title="Standard Deviation"></Field>
  <Field Id="Grid_aggOp_Standard_Deviation_for_Population" Title=" Standard Deviation for Population"></Field>
  <Field Id="Grid_aggOp_Variance" Title="Variance"></Field>
  <Field Id="Grid_aggOp_Variance_of_Population" Title="Variance of Population"></Field>
  <Field Id="Grid_Click_and_drag_to_see_x" Title="Click and drag to see {0}"></Field>
  <Field Id="Grid_Click_on_a_row_to_see_details_about_that_row_here" Title="Click on a row to see details about that row here."></Field>
  <Field Id="Grid_Selected_Rows" Title="Selected Rows:"></Field>
  <Field Id="Grid_Add_To" Title="Add To "></Field>
  <Field Id="Grid_Update" Title="Update "></Field>
  <Field Id="Grid_context_Search" Title="Search"></Field>
  <Field Id="Grid_context_Select_All" Title="Select All"></Field>
  <Field Id="Grid_context_Export" Title="Export"></Field>
  <Field Id="Grid_context_Controls" Title="Controls"></Field>
  <Field Id="Grid_Downloading_All_Records" Title="Downloading All Records..."></Field>
  <Field Id="Grid_Cancel_Download" Title="Cancel Download"></Field>
  <Field Id="Grid_Just_a_moment" Title="Just a moment..."></Field>
  <Field Id="Grid_Grid" Title="Grid"></Field>
  <Field Id="Grid_controlbox_Delete" Title="Delete"></Field>
  <Field Id="Grid_Parseing_data_x_complete" Title="Parseing data. {0]% complete"></Field>
  <Field Id="Grid_Delete_Selected_Rows" Title="Delete Selected Row(s)"></Field>
  <Field Id="Grid_delete_No" Title="No"></Field>
  <Field Id="Grid_delete_Yes" Title="Yes"></Field>
  <Field Id="Grid_Are_you_sure_you_want_to_delete" Title="Are you sure you want to delete the selected row(s)?"></Field>
  <Field Id="Grid_Confirm_delete_row" Title="Confirm delete row."></Field>
  <Field Id="Grid_Confirm_Delete" Title="Confirm Delete."></Field>
  <Field Id="Grid_delete_Refresh" Title="Refresh"></Field>
  <Field Id="Grid_ContextMenu_Search" Title="Search"></Field>
  <Field Id="Grid_ContextMenu_Refresh" Title="Refresh"></Field>
  <Field Id="Grid_ContextMenu_Get_Aggregate_Total" Title="Get Aggregate Total"></Field>
  <Field Id="Grid_ContextMenu_Hide_this_column" Title="Hide this column"></Field>
  <Field Id="Grid_ContextMenu_Order_by_This_Column_Ascending" Title="Order by This Column Ascending"></Field>
  <Field Id="Grid_ContextMenu_Order_by_This_Column_Descending" Title="Order by This Column Descending"></Field>
  <Field Id="Grid_ContextMenu_Download_All_Records" Title="Download All Records"></Field>
  <Field Id="Grid_ContextMenu_Output_to_a_File" Title="Output to a File"></Field>
  <Field Id="Grid_ContextMenu_Select_All" Title="Select All"></Field>
  <Field Id="Grid_ContextMenu_Invert_Selection" Title="Invert Selection"></Field>
  <Field Id="Grid_ContextMenu_Toggle_Details_Pane" Title="Toggle Details Pane"></Field>
  <Field Id="Grid_ContextMenu_AddRemove_Columns" Title="Add/Remove Columns"></Field>
  <Field Id="Grid_This_table_does_not_support_editing__No_primary_key_defined" Title="This table does not support editing.  No primary key defined."></Field>
  <Field Id="Grid_StatusUpdate_Updating_Record" Title="Updating Record"></Field>
  <Field Id="Grid_StatusUpdate_Please_wait_while_your_record_is_updated" Title="Please wait while your record is updated"></Field>
  <Field Id="Grid_EditReturn_Return_To_Editing" Title="Return To Editing"></Field>
  <Field Id="Grid_EditReturn_Refresh_row_and_discarding_any_changes" Title="Refresh row and discarding any changes"></Field>
  <Field Id="Grid_EditReturn_The_row_was_deleted_since_you_last_refreshed_it" Title="The row was deleted since you last refreshed it."></Field>
  <Field Id="Grid_EditReturn_This_row_has_been_deleted" Title="This row has been deleted."></Field>
  <Field Id="Grid_EditReturn_Row_no_longer_exists" Title="Row no longer exists."></Field>
  <Field Id="Grid_This_row_has_changed_msg" Title="This row has changed">This row has changed since the data was last retrieved.  Do you want to save your changes now?  Click Yes to commit your changes to the database anyway.  Click No to discard your changes and retrieve the current data for this row.  Click Cancel to continue editing.</Field>
  <Field Id="Grid_Data_updated_since_last_refresh" Title="Data updated since last refresh."></Field>
  <Field Id="Grid_Data_Timestamp_Mismatch" Title="Data Timestamp Mismatch"></Field>
  <Field Id="Grid_VerColMissmatch_Cancel" Title="Cancel"></Field>
  <Field Id="Grid_VerColMissmatch_No" Title="No"></Field>
  <Field Id="Grid_VerColMissmatch_Click_No_to_discard_your_changes" Title="{0} {1} Click No to discard your changes and retrieve the current data for this row. Click Cancel to continue editing."></Field>
  <Field Id="Grid_SQL_Server_error" Title="SQL Server error."></Field>
  <Field Id="Grid_aggDialog_Calculate" Title="Calculate"></Field>
  <Field Id="Grid_aggDialog_Select_column_and_aggregate_function_to_use" Title="Select column and aggregate function to use."></Field>
  <Field Id="Grid_You_cannot_use_this_aggregate" Title="You cannot use this aggregate function {0} with column {1} because it is the data type {2}."></Field>
  <Field Id="Grid_OutputDialog_Output_to_a_File" Title="Output to a File"></Field>
  <Field Id="Grid_OutputDialog_File_Type" Title="File Type"></Field>
  <Field Id="Grid_OutputDialog_Only_included_selected_rows_and_columns" Title="Only included selected rows and columns."></Field>
  <Field Id="Grid_OutputDialog_Include_header_names_on_first_row" Title="Include header names on first row."></Field>
  <Field Id="Grid_OutputDialog_Send_in_a_compressed_zip_file" Title="Send in a compressed zip file."></Field>
  <Field Id="Grid_OutputDialog_Create" Title="Create"></Field>
  <Field Id="Grid_OutputDialog_Select_what_type_of_file_to_create" Title="Select what type of file to create."></Field>
  <Field Id="Grid_FindDialog_Add_Results_To_Selection" Title="Add Results To Selection"></Field>
  <Field Id="Grid_FindDialog_Find_Next" Title="Find Next"></Field>
  <Field Id="Grid_FindDialog_Find_Previous" Title="Find Previous"></Field>
  <Field Id="Grid_FindDialog_Select_your_search_criteria" Title="Select your search criteria,"></Field>
  <Field Id="Grid_FindDialog_Find_Dialog_Title" Title="Find"></Field>
  <Field Id="Grid_search_You_have_entered_a_value_that_does_not_match" Title="You have entered a value that does not match the type of value execpted for this field. This field is of the type {0}."></Field>
  <Field Id="Grid_Find_Match_x_of_x" Title="Match {0} of {1}"></Field>
  <Field Id="Grid_Reached_the_end_of_the_search" Title="Reached the end of the search results, starting from the beginging."></Field>
  <Field Id="Grid_Reached_the_beginging_of_the_search" Title="Reached the beginging of the search results, starting from the end."></Field>
  <Field Id="Grid_Finding_matches" Title="Finding matches..."></Field>
  <Field Id="Grid_No_matches" Title="No matches"></Field>
  <Field Id="GenericEditor_Add_Create" Title="Add / Create"></Field>
  <Field Id="FormatDate_Jan" Title="Jan"></Field>
  <Field Id="FormatDate_Feb" Title="Feb"></Field>
  <Field Id="FormatDate_Mar" Title="Mar"></Field>
  <Field Id="FormatDate_Apr" Title="Apr"></Field>
  <Field Id="FormatDate_May" Title="May"></Field>
  <Field Id="FormatDate_Jun" Title="Jun"></Field>
  <Field Id="FormatDate_Jul" Title="Jul"></Field>
  <Field Id="FormatDate_Aug" Title="Aug"></Field>
  <Field Id="FormatDate_Sep" Title="Sep"></Field>
  <Field Id="FormatDate_Oct" Title="Oct"></Field>
  <Field Id="FormatDate_Nov" Title="Nov"></Field>
  <Field Id="FormatDate_Dec" Title="Dec"></Field>
  <Field Id="Form_One_or_more_inputs_are_invalid" Title="One or more inputs are invalid."></Field>
  <Field Id="Form_The_following_fields_contain_validation_errors" Title="The following fields contain validation errors:">The following fields contain validation errors:{0}</Field>
  <Field Id="Form_Form_Validation_Error" Title="Form Validation Error"></Field>
  <Field Id="Form_CheckSaveState_Yes" Title="Yes"></Field>
  <Field Id="Form_CheckSaveState_No" Title="No"></Field>
  <Field Id="Form_CheckSaveState_Cancel" Title="Cancel"></Field>
  <Field Id="Form_Do_you_want_to_save_your_changes_now" Title="Do you want to save your changes now?">
    'Do you want to save your changes now?
    Click Yes to save changes and close the record.
    Click No to discard your changes and close the record.
    Click Cancel to continue editing the record.'
  </Field>
  <Field Id="Form_Save_changes" Title="Save changes?"></Field>
  <Field Id="Form_Save_changes_before_closing" Title="Save changes before closing?"></Field>
  <Field Id="Form_Save_Successful" Title="Save Successful"></Field>
  <Field Id="Form_Saved" Title="Saved"></Field>
  <Field Id="Form_record_no_longer_exists" Title="record no longer exists"></Field>
  <Field Id="Form_save_Yes" Title="Yes"></Field>
  <Field Id="Form_save_No" Title="No"></Field>
  <Field Id="Form_save_Cancel" Title="Cancel"></Field>
  <Field Id="Form_This_record_has_changed" Title="This record has changed since the data was last retrieved">
    'This record has changed since the data was last retrieved.  Do you want to save your changes now?
    Click Yes to commit your changes to the database anyway
    Click No to retrieve the current data for this record in a new window.
    Click Cancel to continue editing.
  </Field>
  <Field Id="Form_Data_updated_since_last_refresh" Title="Data updated since last refresh."></Field>
  <Field Id="Form_Data_Timestamp_Mismatch" Title="Data Timestamp Mismatch"></Field>
  <Field Id="Form_serverError_Click_ok_to_return_to_editing" Title="Click ok to return to editing."></Field>
  <Field Id="Form_Internal_Server_error" Title="Internal Server error.,"></Field>
  <Field Id="Form_serverError_Error" Title="Error "></Field>
  <Field Id="Form_This_value_can_only_be_a_number" Title="This value can only be a number."></Field>
  <Field Id="Form_Invalid_value" Title="Invalid value."></Field>
  <Field Id="FileManager_Browse" Title="Browse..."></Field>
  <Field Id="FileManager_upload_Upload_File_Title" Title="Upload File"></Field>
  <Field Id="FileManager_uploadInput_Remove" Title="Remove"></Field>
  <Field Id="FileManager_uploadInput_You_cant_remove_the_last_file" Title="You cannot remove the last file"></Field>
  <Field Id="FileManager_uploadInput_Uploading" Title="Uploading"></Field>
  <Field Id="FileManager_uploadInput_Updating_data" Title="Updating data..."></Field>
  <Field Id="FileManager_uploadInput_Details" Title="Details"></Field>
  <Field Id="FileManager_x_pct_Complete_xMB_of_xMB" Title="{0}% Complete {1}MB of {2}MB"></Field>
  <Field Id="FileManager_Speed_xKBsecond" Title="Speed:{0}KB/second"></Field>
  <Field Id="FileManager_uploadInput_Calculating" Title="Calculating..."></Field>
  <Field Id="FileManager_uploadInput_pct_Complete" Title="{0}% Complete "></Field>
  <Field Id="FileManager__parsing_file_data" Title=" parsing file data."></Field>
  <Field Id="FileManager_uploadInput_Current_file_x" Title="Current file: {0}"></Field>
  <Field Id="FileManager_uploadInput_submit_Upload" Title="Upload"></Field>
  <Field Id="FileManager_uploadInput_Select_one_or_more_files_to_upload" Title="Select one or more files to upload."></Field>
  <Field Id="FileManager_File_Manager_Title" Title="File Manager"></Field>
  <Field Id="FileManager_Schema_Size_of_the_file" Title="Size of the file"></Field>
  <Field Id="FileManager_Schema_Name" Title="Name"></Field>
  <Field Id="FileManager_Schema_Size" Title="Size"></Field>
  <Field Id="FileManager_Schema_File_or_directory_name" Title="File or directory name"></Field>
  <Field Id="FileManager_Schema_Last_time_this_file_was_accessed" Title="Last time this file was accessed."></Field>
  <Field Id="FileManager_Schema_Last_Access_Time" Title="Last Access Time"></Field>
  <Field Id="FileManager_Schema_The_date_this_file_was_created" Title="The date this file was created."></Field>
  <Field Id="FileManager_Schema_Creation_Time" Title="Creation Time"></Field>
  <Field Id="FileManager_Server_error" Title="Server error."></Field>
  <Field Id="FileManager_Are_you_sure_you_want_exit__You_have_unsaved_changes" Title="Are you sure you want exit?  You have unsaved changes."></Field>
  <Field Id="FileManager_editor_defaultname_Untitledtxt" Title="Untitled.txt"></Field>
  <Field Id="FileManager_Text_Editor_" Title="Text Editor "></Field>
  <Field Id="FileManager_editorMenu_File" Title="File"></Field>
  <Field Id="FileManager_editorMenu_Edit" Title="Edit"></Field>
  <Field Id="FileManager_editorMenu_View" Title="View"></Field>
  <Field Id="FileManager_editorMenu_Language" Title="Language"></Field>
  <Field Id="FileManager_editorMenu_Theme" Title="Theme"></Field>
  <Field Id="FileManager_editorMenu_Word_Wrap" Title="Word Wrap"></Field>
  <Field Id="FileManager_FileMenu_New" Title="New"></Field>
  <Field Id="FileManager_FileMenu_Save" Title="Save"></Field>
  <Field Id="FileManager_FileMenu_Save_As" Title="Save As..."></Field>
  <Field Id="FileManager_FileMenu_Exit" Title="Exit"></Field>
  <Field Id="FileManager_EditMenu_Undo" Title="Undo"></Field>
  <Field Id="FileManager_EditMenu_Redo" Title="Redo"></Field>
  <Field Id="FileManager_EditMenu_Find_and_Replace" Title="Find and Replace"></Field>
  <Field Id="FileManager_EditMenu_Go_To" Title="Go To..."></Field>
  <Field Id="FileManager_EditMenu_Goto_Line" Title="Goto Line"></Field>
  <Field Id="FileManager_Line_number_must_be_a_number" Title="Line number must be a number"></Field>
  <Field Id="FileManager_Find_and_Replace" Title="Find and Replace (not fully working)"></Field>
  <Field Id="FileManager_Find_What" Title="Find What"></Field>
  <Field Id="FileManager_Replace_With" Title="Replace With"></Field>
  <Field Id="FileManager_Match_Whole_Word" Title="Match Whole Word"></Field>
  <Field Id="FileManager_Match_Case" Title="Match Case"></Field>
  <Field Id="FileManager_Use_Regular_Expression" Title="Use Regular Expression"></Field>
  <Field Id="FileManager_EditorClose_Yes" Title="Yes"></Field>
  <Field Id="FileManager_EditorClose_No" Title="No"></Field>
  <Field Id="FileManager_EditorClose_Cancel" Title="Cancel"></Field>
  <Field Id="FileManager_EditorClose_Do_you_want_to_save" Title="Do you want to save your changes now">
    Do you want to save your changes now?
    Click Yes to save changes and close.
    Click No to discard your changes and close.
    Click Cancel to continue editing.
  </Field>
  <Field Id="FileManager_Save_changes" Title="Save changes?"></Field>
  <Field Id="FileManager_Save_changes_before_closing" Title="Save changes before closing?"></Field>
  <Field Id="FileManager_SaveAs_Save" Title="Save"></Field>
  <Field Id="FileManager_SaveAs_Cancel" Title="Cancel"></Field>
  <Field Id="FileManager_Save_x_as" Title="Save {0} as..."></Field>
  <Field Id="FileManager_Logical_Drives" Title="Logical Drives"></Field>
  <Field Id="FileManager_TreeContext_Copy" Title="Copy..."></Field>
  <Field Id="FileManager_TreeContext_Move" Title="Move..."></Field>
  <Field Id="FileManager_TreeContext_Rename" Title="Rename..."></Field>
  <Field Id="FileManager_TreeContext_Delete" Title="Delete..."></Field>
  <Field Id="FileManager_Context_Copy_To" Title="Copy To..."></Field>
  <Field Id="FileManager_Context_RenameMove_Single_File" Title="Rename/Move Single File"></Field>
  <Field Id="FileManager_Context_Rename" Title="Rename"></Field>
  <Field Id="FileManager_RenameContext_Cancel" Title="Cancel"></Field>
  <Field Id="FileManager_Invalid_file_name" Title="Invalid file name."></Field>
  <Field Id="FileManager_Enter_the_new_file_name_and_path" Title="Enter the new file name and path"></Field>
  <Field Id="FileManager_Context_Move_To" Title="Move To..."></Field>
  <Field Id="FileManager_Delete_Yes" Title="Yes"></Field>
  <Field Id="FileManager_Delete_No" Title="No"></Field>
  <Field Id="FileManager_Are_you_sure_you_want" Title="Are you sure you want to delete the selected file(s) and/or directoires(s)?  Click yes to continue or click no to abort."></Field>
  <Field Id="FileManager_Confirm_Delete" Title="Confirm Delete"></Field>
  <Field Id="FileManager_Create_Folder" Title="Create Folder"></Field>
  <Field Id="FileManager_MkDir_Cancel" Title="Cancel"></Field>
  <Field Id="FileManager_New_Folder" Title="New Folder"></Field>
  <Field Id="FileManager_File_and_folder_names_cannot_contain_the_following_characters" Title="File and folder names cannot contain the following characters"></Field>
  <Field Id="FileManager_Invalid_folder_name" Title="Invalid folder name."></Field>
  <Field Id="FileManager_Enter_a_name_for_your_new_folder_GroupBox_title" Title="Enter a name for your new folder"></Field>
  <Field Id="FileManager_ContextMenu_Download_File" Title="Download File"></Field>
  <Field Id="FileManager_ContextMenu_Edit" Title="Edit..."></Field>
  <Field Id="FileManager_ContextMenu_Copy" Title="Copy..."></Field>
  <Field Id="FileManager_ContextMenu_Move" Title="Move..."></Field>
  <Field Id="FileManager_ContextMenu_Rename" Title="Rename..."></Field>
  <Field Id="FileManager_ContextMenu_Delete" Title="Delete..."></Field>
  <Field Id="FileManager_ContextMenu_Create_Folder" Title="Create Folder..."></Field>
  <Field Id="FileManager_ContextMenu_Upload_A_File" Title="Upload A File..."></Field>
  <Field Id="FileManager_Select_File" Title="Select File"></Field>
  <Field Id="FileManager_You_must_select_a_file_not_a_folder" Title="You must select a file, not a folder."></Field>
  <Field Id="FileManager_Select_Files" Title="Select File(s)"></Field>
  <Field Id="FileManager_Select_Folder" Title="Select Folder"></Field>
  <Field Id="FileManager_You_must_select_a_folder_not_a_file" Title="You must select a folder, not a file."></Field>
  <Field Id="FileManager_ButtonBar_Copy" Title="Copy"></Field>
  <Field Id="FileManager_ButtonBar_Move" Title="Move"></Field>
  <Field Id="FileManager_ButtonBar_Rename" Title="Rename"></Field>
  <Field Id="FileManager_ButtonBar_New_Folder" Title="New Folder"></Field>
  <Field Id="FileManager_ButtonBar_Delete" Title="Delete"></Field>
  <Field Id="FileManager_ButtonBar_Upload" Title="Upload"></Field>
  <Field Id="FileManager_ButtonBar_Edit" Title="Edit"></Field>
  <Field Id="FileManager_ButtonBar_New" Title="New"></Field>
  <Field Id="FileManager_DetailBar_File_Size" Title="File Size:"></Field>
  <Field Id="FileManager_DetailBar_Type" Title="Type:"></Field>
  <Field Id="FileManager_DetailBar_Created_On" Title="Created On:"></Field>
  <Field Id="FileManager_DetailBar_Last_Modified_On" Title="Last Modified On:"></Field>
  <Field Id="FileManager_x_files_selected_Total_of_x_bytes" Title="{0} files selected.  Total of {1} bytes."></Field>
  <Field Id="FileManager_x_folders_selected" Title="{0} [folders] selected."></Field>
  <Field Id="ConfirmDialog_Cancel" Title="Cancel"></Field>
  <Field Id="ConfirmDialog_Ok" Title="Ok"></Field>
  <Field Id="ConfirmDialog_Confirm" Title="Confirm"></Field>
  <Field Id="ConfirmDialog_Are_you_sure" Title="Are you sure?"></Field>
  <Field Id="Chat_Select_a_channel" Title="Select a channel"></Field>
  <Field Id="Chat_-_Create_a_new_channel_-_" Title="- Create a new channel - "></Field>
  <Field Id="Chat_Name" Title="Name"></Field>
  <Field Id="Chat_Subject" Title="Subject"></Field>
  <Field Id="Chat_Users" Title="Users"></Field>
  <Field Id="Chat_ownerId" Title="ownerId"></Field>
  <Field Id="Chat_Password_Protected" Title="Password Protected"></Field>
  <Field Id="Chat_Join_Conversation" Title="Join Conversation"></Field>
  <Field Id="Chat_Refresh" Title="Refresh"></Field>
  <Field Id="Cha_Add_a_user" Title="- Add a user -"></Field>
  <Field Id="Chat_Account_No" Title="Account No."></Field>
  <Field Id="Chat_Enter_an_Account_No" Title="Enter an Account No."></Field>
  <Field Id="Chat_Select_user" Title="Select user."></Field>
  <!-- Panel Defaults -->
  <Field Id="DefaultPanelItems_Go_to_Admin_Page" Title="Go to Admin Page" Hidden="0">Navigate to the admin page.</Field>
  <Field Id="DefaultPanelItems_Go_to_Home_Page" Title="Go to Home Page" Hidden="0">Navigate to the home page.</Field>
  <Field Id="DefaultPanelItems_Category_Editor" Title="Category Editor" Hidden="0">Edit what items show up in what categories.</Field>
  <Field Id="DefaultPanelItems_Create_New_Item" Title="Create New Item" Hidden="0">Create a new item.</Field>
  <Field Id="DefaultPanelItems_Edit_Existing_Item" Title="Edit Existing Item" Hidden="0">Open an item that you created earlier.</Field>
  <Field Id="DefaultPanelItems_Create_New_Order" Title="Create New Order" Hidden="0">Create a new order for one of your customers.</Field>
  <Field Id="DefaultPanelItems_Edit_Existing_Order" Title="Edit Existing Order" Hidden="0">Open an existing order.  These orders are from the web site, EDI trasfer or manual entry in this program.</Field>
  <Field Id="DefaultPanelItems_Create_New_Account" Title="Create New Account" Hidden="0">Create a new account.</Field>
  <Field Id="DefaultPanelItems_Edit_Existing_Account" Title="Edit Existing Account" Hidden="0">Open an account.</Field>
  <Field Id="DefaultPanelItems_Content" Title="Content" Hidden="0"></Field>
  <Field Id="DefaultPanelItems_Menus" Title="Menus" Hidden="0">Edit menus in the system.</Field>
  <Field Id="DefaultPanelItems_Site_Sections" Title="Site Sections" Hidden="0">Modify and create scripts for sections of pages or entire pages.</Field>
  <Field Id="DefaultPanelItems_Email" Title="Email" Hidden="0">See what email as gone out of the system.</Field>
  <Field Id="DefaultPanelItems_File_Manager" Title="File Manager" Hidden="0">Upload, download and edit files on your web server.</Field>
  <Field Id="DefaultPanelItems_Rendition_Help" Title="Rendition Help" Hidden="0">Get help with Rendition.</Field>
  <Field Id="DefaultPanelItems_Import" Title="Import" Hidden="0">Import items, shipping services, users and more.</Field>
  <Field Id="DefaultPanelItems_Image_Templates" Title="Image Templates" Hidden="0">Change the way the items are modified when you add images to your items.</Field>
  <Field Id="DefaultPanelItems_Refresh_Cache" Title="Refresh Cache" Hidden="0">Refresh the data stored in the memory of the server from the database.</Field>
  <Field Id="DefaultPanelItems_Reloading_site_cache" Title="Reloading site cache..." Hidden="0"></Field>
  <Field Id="DefaultPanelItems_Search" Title="Search" Hidden="0"></Field>
  <Field Id="DefaultPanelItems_SEO" Title="SEO" Hidden="0"></Field>
  <Field Id="DefaultPanelItems_Settings" Title="Settings" Hidden="0">Setup Domain names, site defaults, user defaults, email control, authentication control, image template assignments, URI keys, shipping defaults and redirectors here.</Field>
  <Field Id="DefaultPanelItems_Shipping_Services" Title="Shipping Services" Hidden="0">Edit shipping services.</Field>
  <Field Id="DefaultPanelItems_Site_Stats" Title="Site Stats" Hidden="0">See who's visiting your site and when.</Field>
  <Field Id="DefaultPanelItems_Logon_Logoff" Title="Logon And Logoff" Hidden="0"></Field>
  <Field Id="DefaultPanelItems_Logoff" Title="Logoff" Hidden="0">Logoff of the system.</Field>
  <Field Id="DefaultPanelItems_Logon_as_another_user" Title="Logon as another user" Hidden="0">Logon as another user.</Field>
  <Field Id="DefaultPanelItems_Items_Categories" Title="Items And Categories" Hidden="0"></Field>
  <Field Id="DefaultPanelItems_Orders_and_Accounts" Title="Orders And Accounts" Hidden="0"></Field>
  <Field Id="DefaultPanelItems_Settings_and_Stats" Title="Settings And Stats" Hidden="1"></Field>
  <!-- Commerce Applications -->
  <Field Id="Init_responderKeyName" Title="method"></Field>
  <Field Id="SystemMessages_System_Message" Title="System Message"></Field>
  <Field Id="SystemMessages_Dismiss" Title="Dismiss"></Field>
  <Field Id="SystemMessages_Event_Time" Title="Event Time:"></Field>
  <Field Id="SiteEditor_Reloading_site_cache" Title="Reloading site cache..."></Field>
  <Field Id="SiteEditor_Restarting_application_just_a_moment" Title="Restarting application, just a moment..."></Field>
  <Field Id="SiteEditor_Restarting_Application" Title="Restarting Application..."></Field>
  <Field Id="SiteEditor_Refresh_Cache" Title="Refresh Cache"></Field>
  <Field Id="SiteEditor_Restart_Web_Site" Title="Restart Web Site"></Field>
  <Field Id="SiteEditor_Status" Title="Status"></Field>
  <Field Id="SiteEditor_Status_Code" Title="Status Code"></Field>
  <Field Id="SiteEditor_Description" Title="Description"></Field>
  <Field Id="SiteEditor_Author" Title="Author"></Field>
  <Field Id="SiteEditor_Version" Title="Version"></Field>
  <Field Id="SiteEditor_Enabled" Title="Enabled"></Field>
  <Field Id="SiteEditor_GUID" Title="GUID"></Field>
  <Field Id="SiteEditor_Property" Title="Property"></Field>
  <Field Id="SiteEditor_Value" Title="Value"></Field>
  <Field Id="SiteEditor_Rendition_Information" Title="Rendition Information"></Field>
  <Field Id="SiteEditor_Plugins_Information" Title="Plugins Information"></Field>