<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Fields[
  <!ELEMENT Fields ANY>
  <!ELEMENT Field ANY>
  <!ATTLIST Field Id ID #REQUIRED>
  <!ATTLIST Field Title CDATA #REQUIRED>
  <!ATTLIST Field Hidden CDATA #IMPLIED>
  <!ATTLIST Field DefaultValue CDATA #IMPLIED>
]>
<Fields>
  <Field Id="RenditionInventory_Status_Aging_Pie" Title="Status Aging Pie"></Field>
  <Field Id="RenditionInventory_Status_Aging_Table" Title="Status Aging Table"></Field>
  <Field Id="RenditionInventory_Aging_Pie" Title="Aging Pie"></Field>
  <Field Id="RenditionInventory_Order_Statuses" Title="Order Statuses"></Field>
  <Field Id="RenditionInventory_Aging_Table" Title="Aging Table"></Field>
  <Field Id="Grid_aging_userid" Title="userid" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_0" Title="0" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_5" Title="5" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_15" Title="15" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_30" Title="30" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_45" Title="45" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_60" Title="60" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_120" Title="120" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_aging_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
  <Field Id="Form_ProductionAging_from" Title="From" DefaultValue="From" Hidden="false"></Field>
  <Field Id="Form_ProductionAging_to" Title="To" DefaultValue="To" Hidden="false"></Field>
  <Field Id="Form_ProductionAging_userId" Title="Account No." DefaultValue="Account No." Hidden="false"></Field>
  <Field Id="Form_ProductionAging_groupBy" Title="Grouping" DefaultValue="Grouping" Hidden="false"></Field>
  <Field Id="Form_ProductionPicklist_from" Title="From" DefaultValue="From" Hidden="false"></Field>
  <Field Id="Form_ProductionPicklist_to" Title="To" DefaultValue="To" Hidden="false"></Field>
  <Field Id="Form_ProductionPicklist_userId" Title="Account No." DefaultValue="Account No." Hidden="false"></Field>
  <Field Id="Form_SalesJournal_from" Title="From" DefaultValue="From" Hidden="false"></Field>
  <Field Id="Form_SalesJournal_to" Title="To" DefaultValue="To" Hidden="false"></Field>
  <Field Id="Form_SalesJournal_userId" Title="Account No." DefaultValue="Account No." Hidden="false"></Field>
  <Field Id="Grid_salesJournalByDate_orderDate" Title="orderDate" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_salesJournalByDate_grandTotal" Title="grandTotal" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_salesJournalByDate_taxTotal" Title="taxTotal" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_salesJournalByDate_subTotal" Title="subTotal" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_salesJournalByDate_shippingTotal" Title="shippingTotal" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_salesJournalByDate_discount" Title="discount" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_salesJournalByDate_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_itemNumber" Title="itemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_shortDescription" Title="shortDescription" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_stockStatus" Title="stockStatus" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_reorderPoint" Title="reorderPoint" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_highThreshold" Title="highThreshold" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_volume" Title="volume" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_prebook" Title="prebook" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_wip" Title="wip" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_ats" Title="ats" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_consumed" Title="consumed" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_inventorySnapshot_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_itemNumber" Title="itemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_shortDescription" Title="shortDescription" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_prebook" Title="prebook" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_ats" Title="ats" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_wip" Title="wip" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_volume" Title="volume" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_qty" Title="qty" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_orderNumber" Title="orderNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_shipmentNumber" Title="shipmentNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_serialNumber" Title="serialNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_lineNumber" Title="lineNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_orderDate" Title="orderDate" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_manifest" Title="manifest" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_purchaseOrder" Title="purchaseOrder" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_closed" Title="closed" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_canceled" Title="canceled" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_userId" Title="userId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_handle" Title="handle" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_deliverBy" Title="deliverBy" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_parentItemNumber" Title="parentItemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_division" Title="division" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_size" Title="size" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_swatch" Title="swatch" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_orderId" Title="orderId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_cartId" Title="cartId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_prebook_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_itemNumber" Title="itemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_shortDescription" Title="shortDescription" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_prebook" Title="prebook" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_ats" Title="ats" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_wip" Title="wip" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_volume" Title="volume" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_qty" Title="qty" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_orderNumber" Title="orderNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_shipmentNumber" Title="shipmentNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_serialNumber" Title="serialNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_lineNumber" Title="lineNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_orderDate" Title="orderDate" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_manifest" Title="manifest" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_purchaseOrder" Title="purchaseOrder" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_closed" Title="closed" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_canceled" Title="canceled" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_userId" Title="userId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_handle" Title="handle" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_deliverBy" Title="deliverBy" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_parentItemNumber" Title="parentItemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_division" Title="division" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_size" Title="size" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_swatch" Title="swatch" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_orderId" Title="orderId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_cartId" Title="cartId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_workInProgress_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_itemNumber" Title="itemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_shortDescription" Title="shortDescription" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_prebook" Title="prebook" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_ats" Title="ats" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_wip" Title="wip" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_volume" Title="volume" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_qty" Title="qty" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_orderNumber" Title="orderNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_shipmentNumber" Title="shipmentNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_serialNumber" Title="serialNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_lineNumber" Title="lineNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_orderDate" Title="orderDate" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_manifest" Title="manifest" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_purchaseOrder" Title="purchaseOrder" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_closed" Title="closed" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_canceled" Title="canceled" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_userId" Title="userId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_handle" Title="handle" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_deliverBy" Title="deliverBy" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_parentItemNumber" Title="parentItemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_division" Title="division" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_size" Title="size" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_swatch" Title="swatch" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_orderId" Title="orderId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_cartId" Title="cartId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_allocatedStock_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_itemNumber" Title="itemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_shortDescription" Title="shortDescription" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_prebook" Title="prebook" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_ats" Title="ats" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_wip" Title="wip" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_volume" Title="volume" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_qty" Title="qty" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_orderNumber" Title="orderNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_shipmentNumber" Title="shipmentNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_serialNumber" Title="serialNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_lineNumber" Title="lineNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_orderDate" Title="orderDate" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_manifest" Title="manifest" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_purchaseOrder" Title="purchaseOrder" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_closed" Title="closed" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_canceled" Title="canceled" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_userId" Title="userId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_handle" Title="handle" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_deliverBy" Title="deliverBy" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_parentItemNumber" Title="parentItemNumber" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_division" Title="division" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_size" Title="size" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_swatch" Title="swatch" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_orderId" Title="orderId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_cartId" Title="cartId" Hidden="0" DefaultValue=""></Field>
  <Field Id="Grid_consumedStock_VerCol" Title="VerCol" Hidden="0" DefaultValue=""></Field>
</Fields>